apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-service
spec:
  selector:
    matchLabels:
      app: chatbot-service
  replicas: 2
  template:
    metadata:
      labels:
        app: chatbot-service
    spec:
      containers:
        - name: chatbot-service
          image: rafiksherif/chatbot-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: chatbot-service-configmap
