apiVersion: v1
kind: Service
metadata:
  name: chat-service-external
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      name: ws-port
  type: LoadBalancer
