apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      name: service-port
  type: NodePort
